[package]
name = "sprack_bin"
version = "0.1.0"
authors = ["Vitaliy Stepchik <vitalatron@gmail.com>"]

[dependencies]
rand = "*"
image = "*"
rayon = "*"
sprack = { path = "sprack" }

[[bin]]
name = "sprack"
path = "src/main.rs"
