[package]
name = "sprack-demo"
version = "0.1.0"
authors = ["Vitaliy Stepchik <vitalatron@gmail.com>"]

[[bin]]
name = "rectgen"
path = "src/main.rs"

[dependencies]
rand = "*"
image = "*"
rayon = "*"
docopt = "*"
serde = "*"
serde_derive = "*"
